### ISSUE TITLE
[Fix] Make Signup Screen compatible to Keyboard

### ISSUE THREAD

**Issue by Ashish-AI** [feenotifier/apps#27]
```
When a text field is tapped, the keyboard appears which covers the bottom textfields. 
Apply the logic and fix the issue.
```
In main.dart file replace ```home: MyApp()``` with  ``` home: SignupLandingScreen()```

Also, do the necessary changes for properties of **_GenericTextField(s)_**  on the screen

**Comment by Ashish-AI** [comment]
Assigning this to you @Gagarod.

**Comment by Gagarod** [comment]
@Ashish-AI please check the pull request.
